#!/bin/bash

#clear
###################################
TOKEN=$(cat /etc/lukman/bot_token)
CHAT_ID="-1001826411896"

input_file="/etc/xray/domain"
output=""
while IFS= read -r line; do
    sanitized=$(echo "$line" | awk -F'.' '{print toupper(substr($1,1,1)) tolower(substr($1,2))}')
    output="$output$sanitized"
done < "$input_file"
output_upper=$(echo "$output" | tr '[:lower:]' '[:upper:]')
lastdomain="$output_upper"

rx=$(vnstat -d | tail -n 3 | head -n 1 | awk '{print $2, $3}')
tx=$(vnstat -d | tail -n 3 | head -n 1 | awk '{print $5, $6}')
day=$(vnstat -d | tail -n 3 | head -n 1 | awk '{print $8, $9}')
rate=$(vnstat -d | tail -n 3 | head -n 1 | awk '{print $11, $12}')
date=$(vnstat -d | tail -n 3 | head -n 1 | awk '{print $1}')

total=$(vnstat -d | tail -n 4 | head -n 1 | awk '{print $8, $9}')

MESSAGE="
┌───────────────────┐
<code>      </code>Bandwidth Monitor
└───────────────────┘
<code>   isp   = </code>$lastdomain
<code>   tx/rx = </code>$tx / $rx
<code>   daily = </code>$day
<code>   rate  = </code>$rate
<code>   total = </code>$total
┌───────────────────┐
<code>         </code>$date
└───────────────────┘"

#MESSAGE=$(echo "$MESSAGE" | sed "s/^[a-z0-9]*:/$lastdomain:/")
curl -s -X POST "https://api.telegram.org/bot$TOKEN/sendMessage" -d "chat_id=$CHAT_ID" -d "parse_mode=HTML" -d "text=$MESSAGE" > /dev/null
###################################
