#!/bin/bash

clear
python3 /root/profile/art
vnstat -m

echo ""
read -n 1 -p "Press enter to use menu command or x to exit " titit
echo ""
if [ -z $titit ]; then
  menu; echo ""
elif [ $titit = "x" ]; then
  :
else
  /root/profile/./profile2; echo ""
fi
