#!/bin/bash
clear; sleep 1
echo -e " __          __  _                            "; sleep .1
echo -e " \ \        / / | |                           "; sleep .1
echo -e "  \ \  /\  / ___| | ___ ___  _ __ ___   ___   "; sleep .1
echo -e "   \ \/  \/ / _ | |/ __/ _ \| ,_ , _ \ / _ \  "; sleep .1
echo -e "    \  /\  |  __| | (_| (_) | | | | | |  __/  "; sleep .1
echo -e "   __\/_ \/ \___|_|\___\___/|_| |_| |_|\___]  "; sleep .1
echo -e "  / ____|          | |      (_)               "; sleep .1
echo -e " | |     __ _ _ __ | |_ __ _ _ _ __           "; sleep .1
echo -e " | |    / _  |  _ \| __/ _  | |  _ \          "; sleep .1
echo -e " | |___| (_| | |_) | || (_| | | | | |         "; sleep .1
echo -e "  \_____\__,_| .__/ \__\__,_|_|_| |_|         "; sleep .1
echo -e "             | |                              "; sleep .1
echo -e "             |_|                              "; sleep .5
